##生产配置
server:
  port: 7971
  
spring:
  application:
    #应用名称
    name: eurekaServer

eureka:
  server:
    #自我保护
    enable-self-preservation: false

  instance:
    #实例名
    hostname: eureka8089
    #显示ip
    prefer-ip-address: false
    #心跳间隔
    lease-renewal-interval-in-seconds: 3
    #最大心跳间隔
    lease-expiration-duration-in-seconds: 10

  client:
    #注册
    register-with-eureka: true
    #获取
    fetch-registry: true

    service-url:
      #注册地址
      defaultZone: http://eureka8088:8088/eureka/

config:
    ver: 2333


